menu1/config/routes.rb
Rails.application.routes.draw do
  resources :menus do
    resources :menu_items
  end
  

  root 'home#index'
end

menu1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

menu1/app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_items
  validates :new_menu, presence: true, length: { minimum: 5 }
  validates :description, presence: true
end

menu1/app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
end

menu1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

menu1/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

menu1/app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

  def create
    @menu = Menu.find(params[:menu_id])
    @menu_item = @menu.menu_items.create(menu_item_params)
    redirect_to menu_path(@menu)
  end

  def destroy
    @menu = Menu.find(params[:menu_id])
    @menu_item = @menu.menu_items.find(params[:id])
    @menu_item.destroy
    redirect_to menu_path(@menu)
  end

  private
  def menu_item_params
    params.require(:menu_item).permit(:item, :price, :desription)
  end

end

menu1/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menus_params)

    if @menu.save
      redirect_to @menu
    else
      render :new
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    @menu = Menu.find params[:id]

    if @menu.update(menus_params)
      redirect_to @menu
    else
      render :edit
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    redirect_to menus_path
  end


  private
    def menus_params
      params.require(:menu).permit(:new_menu, :description)
    end

end

menu1/app/helpers/application_helper.rb
module ApplicationHelper
end

menu1/app/helpers/home_helper.rb
module HomeHelper
end

menu1/app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

menu1/app/helpers/menus_helper.rb
module MenusHelper
end

menu1/app/views/home/index.html.erb
<h1>Welcome to Jakes on the Lake!</h1>
<h2>√ out our menus <%= link_to 'click here', menus_path()%>  </h2>

menu1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menu1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

menu1/app/views/menu_items/_form.html.erb
<%= form_for([@menu, @menu.menu_items.build]) do |f| %>
 <p>
   <%= f.label :item %><br>
   <%= f.text_field :item %>
 </p>
 <p>
   <%= f.label :description %><br>
   <%= f.text_area :desription %>
 </p>
 <p>
   <%= f.label :price %><br>
   <%= f.text_area :price %>
 </p>
 <p>
   <%= f.submit %>
 </p>
<% end %>

menu1/app/views/menu_items/_menu_item.html.erb
<p>
  <strong>Item:</strong>
  <%= menu_item.item %><br>
  <strong>Description:</strong>
  <%= menu_item.desription %><br>
  <strong>Price:</strong>
  <%= menu_item.price %><br>
  <%= link_to 'Destroy Dish', [menu_item.menu, menu_item],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

menu1/app/views/menus/_form.html.erb
<%= form_for @menu do |f| %>
<% if @menu.errors.any? %>
  <div>
    <h2>
      Please fix the following errors:
    </h2>
    <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
  to see all your menus <%= link_to 'click here', menus_path() %>  
</p>
<p>
  <%= f.label :new_menu %><br>
  <%= f.text_field :new_menu %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

menu1/app/views/menus/edit.html.erb
<h1>Edit menu</h1>
<%= render 'form' %>

menu1/app/views/menus/index.html.erb
<h1>Your new menu here</h1>
<h3>make a new menu <%= link_to 'click here', new_menu_path() %>   </h3>
<h3>to go home  <%= link_to 'click here', root_path() %>  </h3>
<table>
  <tr>
    <th>Menu Title</th>
    <th>description</th>
    <th>links</th>
  </tr>

  <% @menus.each do |menu| %>
  <tr>
    <td><%= menu.new_menu %></td>
    <td><%= menu.description %></td>
    <td><%= link_to 'show', menu_path(menu)%></td>
    <td><%= link_to 'change me', edit_menu_path(menu)%></td>
    <td><%= link_to 'Obliterate', menu_path(menu), method: :delete,
              data: { confirm: 'Really?' } %></td>
  </tr>
  <% end %>
</table>

menu1/app/views/menus/new.html.erb
<h1>creates new menus</h1>
<%= render 'form' %>

menu1/app/views/menus/show.html.erb
<p>
  to see all your menus <%= link_to 'click here', menus_path() %>
</p>
<p>
  <strong>New menu</strong>
  <%= @menu.new_menu %>
</p>
<p>
  <strong>Description</strong>
  <%= @menu.description %>
</p>
<p>
  <strong>These are the dishes on the menu</strong>
  <%= render @menu.menu_items %>
</p>
 <strong>Please add your menus selections here</strong>

 <table>

 </table>

<%= render 'menu_items/form' %>